# Generated by Django 4.0 on 2021-12-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zomra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('AB+', 'AB+'), ('A-', 'A-'), ('AB-', 'AB-')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='فاعل خير', max_length=200, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('wilaya', models.CharField(max_length=200)),
                ('commun', models.CharField(max_length=200)),
                ('zomra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tbr3App.zomra')),
            ],
        ),
    ]
