# Generated by Django 4.0 on 2021-12-24 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
