# Generated by Django 4.0 on 2021-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0002_person_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='zomra',
            field=models.CharField(max_length=3),
        ),
    ]
