# Generated by Django 4.0 on 2021-12-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0003_alter_person_zomra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, default=213, max_digits=10),
        ),
    ]
