# Generated by Django 4.0 on 2021-12-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0008_alter_person_commun_alter_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='فاعل خير', max_length=200),
        ),
    ]
