# Generated by Django 4.0 on 2021-12-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0011_alter_person_commun_alter_person_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
