# Generated by Django 4.0 on 2021-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0013_alter_person_commun_alter_person_wilaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='zomra',
            field=models.CharField(default='الزمرة', max_length=3),
        ),
    ]
