# Generated by Django 4.0 on 2021-12-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3App', '0014_alter_person_zomra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='فاعل خير', max_length=200),
        ),
    ]
